### PR TITLE
Allow IgnoreByNameSuppressorInspection to ignore inspections that target lists

### PR DESCRIPTION
**Pull request by spawnia**
Additionally, this pull request also allows targeting field arguments such as `Query.findUser.id`.

### CODE REVIEW

**Comment by spawnia** [comment]
@owenvoke Can you please take a look at this?

**Comment by owenvoke** [comment]
Hi @spawnia, apologies for not seeing this before. I haven't really had much time to focus on GraphLint recently.

I'll take a look shortly.

**Review by owenvoke — APPROVED** [review]
LGTM! 👍🏻 Tested on 2 of our projects and it seems to be working correctly. Thanks for your work on this!

**Comment by spawnia** [comment]
Thank you for the quick https://github.com/worksome/graphlint/releases/tag/v0.11.3 release 👍

**Pull request merged**
